version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      dotnet: 3.1
      python: 3.7
      ruby: 2.6
  pre_build:
    commands:
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - git checkout -f "$CODEBUILD_RESOLVED_SOURCE_VERSION"
      #- git submodule init
      #- git submodule update --recursive
      - echo Install Hugo
      # Use known tested version of Hugo
      - wget -q https://github.com/gohugoio/hugo/releases/download/v0.68.1/hugo_0.68.1_Linux-64bit.tar.gz
      - HUGO_TAR="$(find . -name "*Linux-64bit.tar.gz")"
      - tar -xzf $HUGO_TAR
      - chmod +x hugo
      # Copy deployment script so that build stage can access it
      - cp automation/content-build-deploy/deploy.sh /usr/local/bin/
      # Set additional custom build environment variables
      - automation/content-build-deploy/build-env.sh

  build:
    commands:
      - echo Build static web site content
      - ./hugo -D
      - echo Deploy content
      - deploy.sh